sudo: required
services:
        - docker
before_install:
        - docker build -t anoopkr05/react-test -f ./client/Dockerfile.dev ./client
script:
        - docker run -e CI=true anoopkr05/react-test npm run test
after_success:
        - docker build -t anoopkr05/multi-client ./client
        - docker build -t anoopkr05/multi-nginx ./nginx
        - docker build -t anoopkr05/multi-server ./server
        - docker build -t anoopkr05/multi-worker ./worker
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push anoopkr05/multi-client
        - docker push anoopkr05/multi-nginx
        - docker push anoopkr05/multi-server
        - docker push anoopkr05/multi-worker
#deploy:
#        provider: elasticbeanstalk
#        region: "ap-south-1"
#        app: "docker-react"
#        env: "DockerReact-env-1"
#        bucket_name: "elasticbeanstalk-ap-south-1-563415454536"
#        bucket_path: "docker-react"
#        on:
#                branch: master
#        access_key_id: $AWS_ACCESS_KEY
#        secret_access_key: $AWS_SECRET_KEY


